### ISSUE TITLE
  add project to Projects using Docile / Lexicon

### ISSUE THREAD

**Issue by peter1000** [sam81/BDF.jl#10]
hi,

Are you still using Docile/Lexicon for documentation. If so 
I would like to add your project to [Projects using Docile / Lexicon](https://github.com/MichaelHatherly/Docile.jl#projects-using-docile--lexicon)
if that is fine with you.

Thanks.

**Comment by sam81** [comment]
hi, yes, I'm still using Docile/Lexicon for documentation, and I'm happy for you to include BDF.jl to that list

**Comment by peter1000** [comment]
Thanks
