### ISSUE TITLE
ASCIIString deprecation

### ISSUE THREAD

**Issue by sam81** [sam81/BDF.jl#15]
ASCIIString has been deprecated in julia v0.5. I've created a new branch which uses Compat.ASCIIString. In this way all tests pass without deprecation warning on julia v0.4 and v0.5:

https://github.com/sam81/BDF.jl/blob/compat0.5/src/BDF.jl

Previously I had tried going with:

```
    import Compat.String
```

and then replacing all occurences of `ASCIIString` to `String`. This seems cleaner since `ASCIIString` will not exist in future julia releases as far as I understand, but while the tests passed in julia v0.5, they didn't pass in julia v0.4 because `isa(channels, AbstractVector{String})` would return `false` if `channels` was an array of `ASCIIString`.

all these string changes in julia have been a bit confusing. @codles do you have any suggestions on the best way to address these compatibility issues?

**Comment by codles** [comment]
Have the standards for Julia v0.5 stabilised? I tried updating EEG.jl for v0.5 a few months ago, but gave up as v0.5 still seemed in flux.

You could tag a version of BDF.jl for v0.4, then develop for v0.5 and drop legacy support. I try to always use the current release.

**Comment by sam81** [comment]
thanks, sounds like a good plan, dropping v0.4 compatibility once v0.5 is out would remove some clutter
